import { NextRequest, NextResponse } from 'next/server';
import { siteConfig, baseUrl } from 'lib/defaultData/siteConfig';

export async function GET(req: NextRequest) {

    const iconLink = `${baseUrl}/icon.png`;
    const generatedByLink = `${baseUrl}`;
    const generatedByName = `Rsrichsoul`;

  const xslContent = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
    xmlns:html="http://www.w3.org/TR/REC-html40"
    xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes" />
    <xsl:template match="/">
        <html xmlns="http://www.w3.org/1999/xhtml">
            <head>
                <title>XML Sitemap Index</title>
                <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
                <meta name="description" content="Rsrichsoul, şık ve kaliteli erkek giyim ürünleri sunan bir platformdur. Yeni gelenler, indirimdekiler ve popüler ürünlerimizi keşfedin."/>
                <link
                    rel="icon"
                    href="${iconLink}"
                />
                <style type="text/css">
                    body {
                    font-family: Helvetica, Arial, sans-serif;
                    font-size: 13px;
                    color: #545353;
                    }
                    table {
                    border: none;
                    border-collapse: collapse;
                    }
                    #sitemap tr:nth-child(odd) td {
                    background-color: #eee !important;
                    }
                    #sitemap tbody tr:hover td {
                    background-color: #ccc;
                    }
                    #sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
                    color: #000;
                    }
                    #content {
                    margin: 0 auto;
                    width: 1000px;
                    }
                    .expl {
                    margin: 18px 3px;
                    line-height: 1.2em;
                    }
                    .expl a {
                    color: #3464eb;
                    font-weight: 600;
                    }
                    .expl a:visited {
                    color: #3464eb;
                    }
                    a {
                    color: #000;
                    text-decoration: none;
                    }
                    a:visited {
                    color: #777;
                    }
                    a:hover {
                    text-decoration: underline;
                    }
                    td {
                    font-size:11px;
                    }
                    th {
                    text-align:left;
                    padding-right:30px;
                    font-size:11px;
                    }
                    thead th {
                    border-bottom: 1px solid #000;
                    }
                </style>

            </head>
            <body>
                <div id="content">
                    <h1>XML Sitemap Index</h1>
                    <p class="expl"> Generated by <a href="${baseUrl}" target="_blank" rel="noopener">${generatedByName}</a>, this is an XML Sitemap, meant for consumption by search engines.<br /> You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank" rel="noopener">sitemaps.org</a>.</p>
                    <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
                        <p class="expl"> This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)" /> sitemaps. </p>
                        <table id="sitemap" cellpadding="10">
                            <thead>
                                <tr>
                                    <th width="3%">No</th>
                                    <th width="78%">Sitemap</th>
                                    <th width="20%">Last Modified</th>
                                </tr>
                            </thead>
                            <tbody>
                                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                                    <xsl:variable name="sitemapURL">
                                        <xsl:value-of select="sitemap:loc" />
                                    </xsl:variable>
                                    <tr>
                                        <td>
                                            <xsl:value-of select="position()" />
                                        </td>
                                        <td>
                                            <a href="{$sitemapURL}" target="_blank">
                                                <xsl:value-of select="sitemap:loc" />
                                            </a>
                                        </td>
                                        <td>
                                            <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)),concat(' ', substring(sitemap:lastmod,20,6)))" />
                                        </td>
                                    </tr>
                                </xsl:for-each>
                            </tbody>
                        </table>
                    </xsl:if>
                </div>
            </body>
        </html>
    </xsl:template>
</xsl:stylesheet>`;

  return new NextResponse(xslContent, {
    headers: {
      'Content-Type': 'application/xml',
    },
  });
}
