import React, { DetailedHTMLProps, HtmlHTMLAttributes } from "react";

interface HtmlProps
  extends DetailedHTMLProps<
    HtmlHTMLAttributes<HTMLHtmlElement>,
    HTMLHtmlElement
  > {
  xmlns?: string;
}
const SitemapIndexXSLTemplate = ({
  iconLink,
  generatedByLink,
  sitemapsOrgLink,
}) => (
  <html
    lang="en-US"
    xmlns="http://www.w3.org/1999/xhtml"
    {...({ xmlns: "http://www.w3.org/1999/xhtml" } as HtmlProps)}
  >
    <head>
      <title>XML Sitemap Index</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta
        name="description"
        content="Rsrichsoul, şık ve kaliteli erkek giyim ürünleri sunan bir platformdur. Yeni gelenler, indirimdekiler ve popüler ürünlerimizi keşfedin."
      />
      <link rel="icon" href={iconLink} />
      <style>
        {`
          body {
            font-family: Helvetica, Arial, sans-serif;
            font-size: 13px;
            color: #545353;
          }
          table {
            border: none;
            border-collapse: collapse;
          }
          #sitemap tr:nth-child(odd) td {
            background-color: #eee !important;
          }
          #sitemap tbody tr:hover td {
            background-color: #ccc;
          }
          #sitemap tbody tr:hover td, #sitemap tbody tr:hover td a {
            color: #000;
          }
          #content {
            margin: 0 auto;
            width: 1000px;
          }
          .expl {
            margin: 18px 3px;
            line-height: 1.2em;
          }
          .expl a {
            color: #da3114;
            font-weight: 600;
          }
          .expl a:visited {
            color: #da3114;
          }
          a {
            color: #000;
            text-decoration: none;
          }
          a:visited {
            color: #777;
          }
          a:hover {
            text-decoration: underline;
          }
          td {
            font-size: 11px;
          }
          th {
            text-align: left;
            padding-right: 30px;
            font-size: 11px;
          }
          thead th {
            border-bottom: 1px solid #000;
          }
        `}
      </style>
    </head>
    <body>
      <div id="content">
        <h1>XML Sitemap Index</h1>
        <p className="expl">
          Generated by{" "}
          <a href={generatedByLink} target="_blank" rel="noopener">
            Havassme
          </a>
          , this is an XML Sitemap, meant for consumption by search engines.
          <br />
          You can find more information about XML sitemaps on{" "}
          <a href={sitemapsOrgLink} target="_blank" rel="noopener">
            sitemaps.org
          </a>
          .
        </p>
        <p>
          <a href={sitemapsOrgLink}>Learn more about XML sitemaps.</a>
        </p>
      </div>
    </body>
  </html>
);

export default SitemapIndexXSLTemplate;
