import { siteConfig, baseUrl } from 'lib/defaultData/siteConfig';

export const defaultRobotsSettings = {
  rules: [
    { userAgent: "*", allow: "/" },
    {
      userAgent: "*",
      disallow: [
        "/dashboard/",
        "/sr",
        "/profilim",
        "/hesabim",
        "/sepetim",
        "/auth/*",
        "/admin",
        "/yonetim",
        "/arama",
        "/filtre",
        "/kampanya",
        "/indirim",
        "/ozel-teklifler",
        "/duyurular",
        "/haberler",
        "/404",
        "/hata",
        "/hesap-ayarlari",
        "/siparis-gecmisi",
        "/teslimat",
        "/odeme",
        "/search",
        "/auth/giris-yap",
        "/auth/cikis-yap",
        "/auth/kayit-ol",
        "/auth/sifremi-unuttum",
        "/auth/sifremi-resetle",
        "/kuponlarim",
        "/ozel",
        "/sana-ozel",
        "/kuponlarim",
        "/kargo-takibi",
        "/favorilerim",
        "/siparislerim",
        "/ozel-mesajlarim",
        "/uye-bilgilerim",
        "/adreslerim",
        "/sr?category=*",
        "/sr?size=*",
        "/sr?color=*",
        "/sr?price=*",
        "/sr?store=*",
        "/sr?brand=*",
        "/sr?rating=*",
        "/sr?coupon=*",
        "/sr?discount=*",
        "/sr?basketDiscount=*"
      ]
    }
  ],
  sitemap: `${baseUrl}/sitemap_index.xml`,
};
